name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Create ECR repository
      run: |
        # Check if repository exists, create if it doesn't
        if ! aws ecr describe-repositories --repository-names backend --region us-east-1 > /dev/null 2>&1; then
          echo "Creating ECR repository: backend"
          aws ecr create-repository --repository-name backend --region us-east-1
        else
          echo "ECR repository already exists: backend"
        fi
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build Docker image
      run: docker build -t backend:latest ./ecommerce-platform/api
      
    - name: Tag Docker image
      run: docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/backend:latest
      
    - name: Push Docker image
      run: docker push ${{ steps.login-ecr.outputs.registry }}/backend:latest

    - name: Verify image was pushed
      run: |
        aws ecr describe-images --repository-name backend --region us-east-1