name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push backend image
      run: |
        docker build -t backend:latest ./ecommerce-platform/api
        docker tag backend:latest ${{ secrets.ECR_REGISTRY }}/backend:latest
        docker push ${{ secrets.ECR_REGISTRY }}/backend:latest

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: api/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('api/package-lock.json') }}

        ## Adding changes