name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ecommerce-platform/api
      
    - name: Clear Jest cache
      run: npx jest --clearCache
      working-directory: ecommerce-platform/api
      
    - name: Run tests with correct configuration
      run: npx jest --rootDir . --passWithNoTests
      working-directory: ecommerce-platform/api
      
    - name: Build application
      run: npm run build
      working-directory: ecommerce-platform/webapp

    